# Generated by Django 5.1.1 on 2025-06-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mt5data", "0003_trade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preferences",
            name="sectors",
        ),
    ]
